site_name: Guía básica sobre Bitcoin
site_description: Aprende lo esencial sobre Bitcoin y la tecnología blockchain
site_author: Tu Nombre

theme:
  name: 'material'

nav:
  - Inicio: index.md
  - Introducción:
      - ¿Qué es Bitcoin?: seccion1/tema1.md
      - Blockchain y funcionamiento: seccion1/tema2.md
  - Curiosidades: seccion2.md

site_author: "Hilya"

# Activar navegación ordenada
nav_sort: case_insensitive

# Definir navegación
just_the_docs:
  navigation:
    - title: Sección 2
      url: /seccion2
    - title: Sección 1
      children:
        - title: Tema 1
          url: /seccion1/tema1
        - title: Tema 2
          url: /seccion1/tema2


title: Documentación Bitcoin
theme: just-the-docs
baseurl: "/documentacion-bitcoin"
